// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ImgSyncerClient is the client API for ImgSyncer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImgSyncerClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type imgSyncerClient struct {
	cc grpc.ClientConnInterface
}

func NewImgSyncerClient(cc grpc.ClientConnInterface) ImgSyncerClient {
	return &imgSyncerClient{cc}
}

func (c *imgSyncerClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/img_syncer.ImgSyncer/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImgSyncerServer is the server API for ImgSyncer service.
// All implementations must embed UnimplementedImgSyncerServer
// for forward compatibility
type ImgSyncerServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedImgSyncerServer()
}

// UnimplementedImgSyncerServer must be embedded to have forward compatible implementations.
type UnimplementedImgSyncerServer struct {
}

func (UnimplementedImgSyncerServer) Hello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedImgSyncerServer) mustEmbedUnimplementedImgSyncerServer() {}

// UnsafeImgSyncerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImgSyncerServer will
// result in compilation errors.
type UnsafeImgSyncerServer interface {
	mustEmbedUnimplementedImgSyncerServer()
}

func RegisterImgSyncerServer(s grpc.ServiceRegistrar, srv ImgSyncerServer) {
	s.RegisterService(&ImgSyncer_ServiceDesc, srv)
}

func _ImgSyncer_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/img_syncer.ImgSyncer/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImgSyncer_ServiceDesc is the grpc.ServiceDesc for ImgSyncer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImgSyncer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "img_syncer.ImgSyncer",
	HandlerType: (*ImgSyncerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _ImgSyncer_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/img_syncer.proto",
}
