
// Objective-C API for talking to the following Go packages
//
//	github.com/fregie/img_syncer/server/run
//
// File is generated by gomobile bind. Do not edit.
#ifndef __RUN_FRAMEWORK_H__
#define __RUN_FRAMEWORK_H__

#include "Run.objc.h"
#include "Universe.objc.h"

#endif
