// Objective-C API for talking to github.com/fregie/img_syncer/server/run Go package.
//   gobind -lang=objc github.com/fregie/img_syncer/server/run
//
// File is generated by gobind. Do not edit.

#ifndef __Run_H__
#define __Run_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@interface Run : NSObject
// skipped variable Debug with unsupported type: *log.Logger

// skipped variable Error with unsupported type: *log.Logger

// skipped variable Info with unsupported type: *log.Logger

@end

FOUNDATION_EXPORT NSString* _Nonnull RunRunGrpcServer(NSError* _Nullable* _Nullable error);

#endif
